Fixed File layout for Franz 5
alexander-schranz/franz-xmpp-client pull request #3
Opened 2018-01-10 16:06 UTC by agodlydeciple

updated package.json and webview.js to work with the newest version of Franz.

2018-01-10 16:07 UTC, agodlydeciple commented
after Merge, feature request needs to be submitted to Franz repo Feature section in order to be added.

2018-02-20 10:36 UTC, alexander-schranz requested changes

2018-02-20 10:36 UTC, alexander-schranz commented on package.json
> +    "version": "1.0.0",
can you increase the version 2.0.0?

2018-03-19 14:26 UTC, stevenroose commented
Does this mean that this is currently broken with latest Franz?

2018-03-19 14:29 UTC, alexander-schranz approved these changes

2018-03-19 14:29 UTC, merged

2018-03-19 14:29 UTC, alexander-schranz commented
@stevenroose this PR should fix the Franz 5 support

2018-03-19 14:41 UTC, alexander-schranz commented
@agodlydeciple thank you